packages:
  - 'portals/*'
  - 'bff/*'
  - 'services/*/*'
  - 'packages/shared/shared'
  - 'packages/core/*'
  - 'packages/platform/*'
  - 'packages/design/design-tokens'
  - 'packages/design/design-ui'
  - 'packages/design/design-system'
  - 'packages/design/design-preview'
  - 'tools/*'
