packages:
  - 'portals/*'
  - 'agent-studio/*'
  - 'agent-server/*'
  - 'business/*'
  - 'bff/*'
  - 'services/*/*'
  - 'packages/shared/shared'
  - 'packages/core/*'
  - 'packages/ai/model-runtime-client'
  - 'packages/platform/*'
  - 'packages/design/design-system'
  - 'tools/*'
