export const TOKEN_PG_POOL = Symbol("TOKEN_PG_POOL");
export const REFRESH_TOKEN_REPOSITORY = Symbol("REFRESH_TOKEN_REPOSITORY");
export const OPERATOR_REFRESH_TOKEN_REPOSITORY = Symbol(
  "OPERATOR_REFRESH_TOKEN_REPOSITORY",
);
