#!/usr/bin/env bash
# deploy/scripts/32-provision-service-db-roles.sh
# TD-018 生产切换步①：为非-owner 服务角色设置真实密码 + 生成 platform-app.env。
# @package  @vxture/repo
# @layer    Infrastructure
# @category deployment-script
# @author   AI-Generated
# @date     2026-07-05
#
# 前提：97_service_roles.sql 已随 apply.sh 进活库（platform_svc / reporting_ro
#   角色已存在，密码为 REPLACE_ME 占位，不可登录使用）。
# 动作：
#   1. 生成两个随机密码（不落日志）；
#   2. ALTER ROLE 设置真实密码（经 owner 连接，owner=容器超级用户可 ALTER ROLE）；
#   3. 写 /srv/vxture/runtime/secrets/platform-app.env（0600）——compose 中该文件
#      排在 platform.env 之后，仅对 5 个服务容器覆盖 DATABASE_URL（TD-018）。
# 幂等：platform-app.env 已存在则跳过（不轮换）；FORCE_ROTATE=yes 才重新生成
#   密码并覆写（轮换后须 recreate 5 个服务容器）。
# 运行：CONFIRM_PROVISION_SVC_ROLES=yes bash scripts/32-provision-service-db-roles.sh
# 后续步②：确保 compose.platform.yml 已含 platform-app.env（本仓库同批变更），
#   recreate 5 容器（正常走 deploy-production；或手动 compose up -d --force-recreate
#   --no-deps auth-bff website-bff console-bff admin-bff model-platform）。
set -euo pipefail

RUNTIME_DIR="${RUNTIME_DIR:-/srv/vxture/runtime}"
SECRETS_DIR="$RUNTIME_DIR/secrets"
APP_ENV="$SECRETS_DIR/platform-app.env"
PLATFORM_ENV="$SECRETS_DIR/platform.env"
PG_CONTAINER="${PG_CONTAINER:-vx-platform-pg}"

if [ "${CONFIRM_PROVISION_SVC_ROLES:-}" != "yes" ]; then
  echo "错误：需显式确认。CONFIRM_PROVISION_SVC_ROLES=yes bash scripts/32-provision-service-db-roles.sh" >&2
  exit 1
fi
[ -f "$PLATFORM_ENV" ] || { echo "错误：缺少 $PLATFORM_ENV" >&2; exit 1; }

if [ -f "$APP_ENV" ] && [ "${FORCE_ROTATE:-}" != "yes" ]; then
  echo "  [skip] $APP_ENV 已存在（不轮换）。轮换：FORCE_ROTATE=yes 重跑（之后须 recreate 5 容器）。"
  exit 0
fi

# DB 名从 owner DATABASE_URL 提取（保持与 platform.env 单一来源一致）。
DB_NAME="$(grep -E '^DATABASE_URL=' "$PLATFORM_ENV" | tail -n1 | sed -E 's#.*/([^/?]+)(\?.*)?$#\1#')"
DB_OWNER="$(grep -E '^DATABASE_URL=' "$PLATFORM_ENV" | tail -n1 | sed -E 's#^DATABASE_URL=postgres(ql)?://([^:]+):.*#\2#')"
[ -n "$DB_NAME" ] && [ -n "$DB_OWNER" ] || { echo "错误：无法从 platform.env 解析 DB 名/owner" >&2; exit 1; }

echo "=== TD-018 provision service DB roles (db=$DB_NAME, owner=$DB_OWNER) ==="

# 角色须已由 97_service_roles.sql 建立——本脚本只设密码，不建角色（单一权威在 DDL）。
for r in platform_svc reporting_ro; do
  n="$(docker exec "$PG_CONTAINER" psql -U "$DB_OWNER" -d "$DB_NAME" -tAc \
      "select count(*) from pg_roles where rolname='$r'")"
  [ "$n" = "1" ] || { echo "错误：角色 $r 不存在——先经 db-init 让 97_service_roles.sql 进库。" >&2; exit 1; }
done

PW_SVC="$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
PW_RO="$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"

docker exec "$PG_CONTAINER" psql -U "$DB_OWNER" -d "$DB_NAME" -q \
  -c "ALTER ROLE platform_svc PASSWORD '$PW_SVC';" \
  -c "ALTER ROLE reporting_ro PASSWORD '$PW_RO';"
echo "  [ok] ALTER ROLE 密码已设置（platform_svc / reporting_ro）"

umask 177
cat > "$APP_ENV" <<EOF
# Generated by 32-provision-service-db-roles.sh — DO NOT COMMIT.
# App-runtime DB credentials (TD-018): overrides DATABASE_URL for the 5 platform
# service containers only; owner connection stays in platform.env for DDL/seed/verify.
DATABASE_URL=postgresql://platform_svc:$PW_SVC@$PG_CONTAINER:5432/$DB_NAME
REPORTING_RO_DATABASE_URL=postgresql://reporting_ro:$PW_RO@$PG_CONTAINER:5432/$DB_NAME
EOF
chmod 600 "$APP_ENV"
echo "  [ok] $APP_ENV 写入（0600）"

# 冒烟：以新凭据各连一次（能连 + 能读）。
docker exec "$PG_CONTAINER" env PGPASSWORD="$PW_SVC" psql -U platform_svc -d "$DB_NAME" -tAc \
  "select count(*) from access.roles" >/dev/null && echo "  [ok] platform_svc 连接+读取冒烟通过"
docker exec "$PG_CONTAINER" env PGPASSWORD="$PW_RO" psql -U reporting_ro -d "$DB_NAME" -tAc \
  "select count(*) from access.roles" >/dev/null && echo "  [ok] reporting_ro 连接+读取冒烟通过"

echo "=== done。下一步：recreate 5 个服务容器（compose 已含 platform-app.env 的版本部署时自动生效）==="
