/**
 * operator-public.router.ts — PUBLIC operator self-service completion (B9-P1b-β).
 * @package @vxture/bff-auth
 *
 * The operator-facing side of the admin-delegated password reset: the operator opens the
 * reset link (generated by admin via the internal endpoint) and sets a new password here.
 * NO InternalAuthGuard — this is PUBLIC; authorization IS the single-use, short-lived,
 * high-entropy Redis token. Realm-isolated (only admin.operator_* via the operator repo).
 * The password never leaves this process except as an Argon2id hash. On success all
 * sessions are (re-)revoked so the operator starts fresh.
 *
 * Design: docs/design/identity-platform-internal-delegation.md §11c step 4.
 */
import {
  BadRequestException,
  Body,
  Controller,
  HttpCode,
  HttpStatus,
  Inject,
  Post,
} from "@nestjs/common";
import { PgOperatorRepository } from "@vxture/service-iam";
import { OperatorRefreshTokenRepository } from "../token/operator-refresh-token.repository";
import { RedisService } from "../redis/redis.service";

// Operators are privileged; enforce a higher floor than the customer flow (8).
const OPERATOR_PASSWORD_MIN_LENGTH = 12;

@Controller("auth/operator")
export class OperatorPublicRouter {
  constructor(
    @Inject(RedisService)
    private readonly redis: RedisService,
    @Inject(PgOperatorRepository)
    private readonly operators: PgOperatorRepository,
    @Inject(OperatorRefreshTokenRepository)
    private readonly refreshTokens: OperatorRefreshTokenRepository,
  ) {}

  /**
   * Complete an admin-delegated reset OR a create-operator initial setup — both
   * mint the SAME single-use token (storeOperatorPasswordReset), so this one
   * endpoint serves either. Consumes the token, sets the new operator password
   * (Argon2id), and revokes all sessions. Errors are generic to avoid leaking
   * whether a token/operator exists.
   *
   * TD-017 §③⑤: successfully completing this flow proves the caller controls
   * the email the token was mailed to, so email_verified is (re-)set true here.
   * For reset it's a no-op (delivery already required emailVerified=true); for
   * create it's the FIRST time trust is established for that address — a
   * brand-new account has no credential yet, so an as-yet-unverified email
   * carries no takeover value (contrast: rewriting an EXISTING credentialed
   * account's email, which the reset-password delivery gate refuses at §③).
   */
  @Post("reset-password")
  @HttpCode(HttpStatus.OK)
  async resetPassword(
    @Body() body: { token?: unknown; password?: unknown },
  ): Promise<{ ok: true }> {
    const token = typeof body.token === "string" ? body.token : "";
    const password = typeof body.password === "string" ? body.password : "";
    if (!token) {
      throw new BadRequestException("invalid_token");
    }
    if (password.length < OPERATOR_PASSWORD_MIN_LENGTH) {
      throw new BadRequestException("weak_password");
    }
    const operatorId = await this.redis.consumeOperatorPasswordReset(token);
    if (!operatorId) {
      throw new BadRequestException("invalid_or_expired_token");
    }
    const ok = await this.operators.setOperatorPassword(operatorId, password, {
      forceChange: false,
    });
    if (!ok) {
      throw new BadRequestException("invalid_or_expired_token");
    }
    await this.operators.markOwnEmailVerified(operatorId);
    await this.refreshTokens.revokeAllForOperator(operatorId);
    return { ok: true };
  }
}
